language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  
before_script:
  - composer self-update
  - composer install --dev

script: 
  - php vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v
notifications:
  email:
    - ricardojesus.ruizcruz@gmail.com
