web:
    image: rrcfesc/dockerfilesmagento2:latest
    ports:
        - "91:80"
        - "92:443"
        - "223:22"
    volumes:
        - ./:/var/www/html
        - ~/.ssh:/home/magento2/.ssh
    environment:
        - WEBSERVER_USER=www-data
        - MAGENTO_USER=magento2
        - CURRENT_USER_UID=1001
        - MAGENTO_GROUP=1001
    links:
        - mysql
    container_name: cicore-web
mysql:
    image: mysql:5.7
    ports:
      - 3333:3306
    environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=magento2
    container_name: cicore-db